"""Play segmentation and observed geometry analytics."""

from football_vision.analytics.formations import FormationSnapshot, analyze_formation
from football_vision.analytics.routes import RouteAnalysis, analyze_route
from football_vision.analytics.play import MetricValue, PlayAnalysis, analyze_play
from football_vision.analytics.events import PlayEvent, detect_events

from football_vision.analytics.segmentation import (
    DEFAULT_BASELINE_MAX_FRACTION,
    DEFAULT_BASELINE_MIN_FRAMES,
    DEFAULT_CONFIDENCE_REFERENCE_CONTRAST,
    DEFAULT_MIN_PLAY_FRAMES,
    DEFAULT_MIN_QUIET_FRAMES,
    DEFAULT_MIN_SUSTAINED_FRAMES,
    DEFAULT_MIN_TRACKS,
    DEFAULT_MOTION_SPEED_THRESHOLD_YD_S,
    DEFAULT_ONSET_MIN_FRACTION,
    MAX_CONFIDENCE,
    REASON_AUTOMATIC_DISABLED,
    REASON_BASELINE_EVIDENCE_GAPS,
    REASON_COORDINATE_CHANGE,
    REASON_INSUFFICIENT_MEASURED_SAMPLES,
    REASON_INSUFFICIENT_TRACKS,
    REASON_NO_MOTION_CESSATION,
    REASON_NO_PRIOR_MOTION,
    REASON_NO_QUIESCENT_BASELINE,
    REASON_NO_SNAP_FOR_END_SEARCH,
    REASON_NO_SUSTAINED_ONSET,
    REASON_NO_TRAJECTORIES,
    REASON_NO_TRAJECTORY_FRAMES,
    REASON_WINDOW_TOO_SHORT,
    REFUSAL_REASONS,
    CollectiveMotionSegmenter,
    MotionEvidence,
    PlaySegmenter,
    build_motion_evidence,
)

__all__ = [
    "FormationSnapshot",
    "analyze_formation",
    "RouteAnalysis",
    "analyze_route",
    "MetricValue",
    "PlayAnalysis",
    "analyze_play",
    "PlayEvent",
    "detect_events",

    "CollectiveMotionSegmenter",
    "MotionEvidence",
    "PlaySegmenter",
    "build_motion_evidence",
    "REFUSAL_REASONS",
    "REASON_AUTOMATIC_DISABLED",
    "REASON_BASELINE_EVIDENCE_GAPS",
    "REASON_COORDINATE_CHANGE",
    "REASON_INSUFFICIENT_MEASURED_SAMPLES",
    "REASON_INSUFFICIENT_TRACKS",
    "REASON_NO_MOTION_CESSATION",
    "REASON_NO_PRIOR_MOTION",
    "REASON_NO_QUIESCENT_BASELINE",
    "REASON_NO_SNAP_FOR_END_SEARCH",
    "REASON_NO_SUSTAINED_ONSET",
    "REASON_NO_TRAJECTORIES",
    "REASON_NO_TRAJECTORY_FRAMES",
    "REASON_WINDOW_TOO_SHORT",
    "DEFAULT_MOTION_SPEED_THRESHOLD_YD_S",
    "DEFAULT_ONSET_MIN_FRACTION",
    "DEFAULT_BASELINE_MAX_FRACTION",
    "DEFAULT_BASELINE_MIN_FRAMES",
    "DEFAULT_MIN_SUSTAINED_FRAMES",
    "DEFAULT_MIN_TRACKS",
    "DEFAULT_MIN_QUIET_FRAMES",
    "DEFAULT_MIN_PLAY_FRAMES",
    "DEFAULT_CONFIDENCE_REFERENCE_CONTRAST",
    "MAX_CONFIDENCE",
]
